### PR TITLE
Ad add tab completion

### LINKED ISSUE #8: Tab completion
i thought may be we want to implement a tab-completion for the available commands and their values (list of countries for example)

### PR DESCRIPTION
**Pull request by amitay87**

### CODE REVIEW

**Comment by amitay87** [comment]
I think it's still not finished. I think I need to fix some things

**Comment by amitay87** [comment]
I deceide to remove the alias for now, because there is already a `coronapy` command.
now the pull request is ready :-)

**Comment by amitay87** [comment]
I removed the alias for now because there is already a `coronpy` command.
So, pull request is ready :-)

**Comment by amitay87** [comment]
HI @MouadBH
I would be glad to hear your opinion about the pull request
should I continue this direction? (I planned to add autocompletion for countries)

**Comment by MouadBH** [comment]
Thank you @amitay87 for you contribution.

**Pull request merged**
